"use client";

import { Bookmark, Camera, Check, Image as ImageIcon, Plus, X } from "lucide-react";
import { useState } from "react";
import { createLocalId, readPlaylists, savePlaylists, type LocalPlaylist } from "@/lib/local-playlists";

export function PlaylistDialog({ animeId, onClose }: { animeId: string; onClose: () => void }) {
  const [playlists, setPlaylists] = useState<LocalPlaylist[]>(readPlaylists);
  const [name, setName] = useState(""); const [cover, setCover] = useState("");
  const update = (next: LocalPlaylist[]) => { savePlaylists(next); setPlaylists(next); window.dispatchEvent(new Event("anithink:playlists-changed")); };
  const createPlaylist = () => { const trimmed = name.trim(); if (!trimmed) return; update([{ id: createLocalId(), name: trimmed, cover: cover.trim(), animeIds: [animeId], createdAt: Date.now() }, ...playlists]); setName(""); setCover(""); };
  const uploadCover = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => setCover(String(reader.result)); reader.readAsDataURL(file); };
  const toggleAnime = (id: string) => update(playlists.map((playlist) => playlist.id !== id ? playlist : { ...playlist, animeIds: playlist.animeIds.includes(animeId) ? playlist.animeIds.filter((anime) => anime !== animeId) : [...playlist.animeIds, animeId] }));

  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-background/85 p-3 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Плейлисты">
    <div className="max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-border bg-card p-5 shadow-panel md:p-6">
      <div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-accent">Коллекция</p><h2 className="font-display text-2xl font-bold">В плейлисты</h2></div><button type="button" onClick={onClose} className="rounded-xl border border-border p-2 text-muted hover:text-foreground" aria-label="Закрыть"><X /></button></div>
      <div className="mt-5 grid gap-5 md:grid-cols-[1fr_240px]">
        <div><p className="mb-2 text-sm font-semibold">Добавить в существующий</p><div className="max-h-64 space-y-2 overflow-y-auto pr-1 scrollbar-cyber">{playlists.length ? playlists.map((playlist) => { const selected = playlist.animeIds.includes(animeId); return <button key={playlist.id} type="button" onClick={() => toggleAnime(playlist.id)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left transition ${selected ? "border-accent bg-accent/10" : "border-border bg-surface hover:border-accent/60"}`}>{playlist.cover ? <img src={playlist.cover} alt="" className="h-12 w-12 rounded-xl object-cover" /> : <span className="flex h-12 w-12 items-center justify-center rounded-xl bg-accent/10 text-accent"><Bookmark className="h-5 w-5" /></span>}<span className="min-w-0 flex-1"><b className="block truncate text-sm">{playlist.name}</b><span className="text-xs text-muted">{playlist.animeIds.length} аниме</span></span>{selected && <Check className="h-5 w-5 text-accent" />}</button>; }) : <p className="rounded-2xl border border-dashed border-border p-5 text-sm text-muted">Создайте первый плейлист справа.</p>}</div></div>
        <div className="rounded-2xl border border-border bg-surface-2/50 p-4"><p className="text-sm font-semibold">Новый плейлист</p><div className="mt-3 aspect-video overflow-hidden rounded-xl border border-border bg-surface">{cover ? <img src={cover} alt="Предпросмотр обложки" className="h-full w-full object-cover" /> : <span className="flex h-full flex-col items-center justify-center gap-2 text-xs text-muted"><ImageIcon className="h-6 w-6 text-accent" />Предпросмотр обложки</span>}</div><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Название" className="mt-3 w-full rounded-xl border border-border bg-surface px-3 py-2.5 text-sm outline-none focus:border-accent" /><input value={cover} onChange={(event) => setCover(event.target.value)} placeholder="Ссылка на обложку" className="mt-2 w-full rounded-xl border border-border bg-surface px-3 py-2.5 text-sm outline-none focus:border-accent" /><label className="mt-2 flex min-h-10 cursor-pointer items-center justify-center gap-2 rounded-xl border border-border text-xs font-semibold text-muted hover:text-accent"><Camera className="h-4 w-4" />Загрузить обложку<input type="file" accept="image/*" className="hidden" onChange={(event) => uploadCover(event.target.files?.[0])} /></label><button type="button" onClick={createPlaylist} disabled={!name.trim()} className="mt-2 flex min-h-10 w-full items-center justify-center gap-2 rounded-xl bg-accent px-3 text-sm font-bold text-background disabled:opacity-40"><Plus className="h-4 w-4" />Создать и добавить</button></div>
      </div>
    </div>
  </div>;
}
